feat: RSS feed
WoowaCrew/WoowaCrew pull request #144
Opened 2019-12-17 08:49 UTC by vsh123

resolved: #138 

## RSS 등록페이지(관리자)
<img width="1401" alt="스크린샷 2019-12-17 오후 5 46 13" src="https://user-images.githubusercontent.com/32254689/70979769-834a9180-20f5-11ea-9bc2-f24b12840d70.png">

## 피드게시판

<img width="799" alt="스크린샷 2019-12-17 오후 5 46 21" src="https://user-images.githubusercontent.com/32254689/70979790-8b0a3600-20f5-11ea-8210-bbbfa22b01f3.png">

2019-12-17 10:13 UTC, pkch93 requested changes
고생했어요 반 :) 몇몇 의문이 든점 피드백 남겼으니 확인해줘요!

2019-12-17 10:13 UTC, pkch93 commented on src/acceptance-test/java/woowacrew/feed/controller/FeedApiControllerTest.java
> +    void 둘중_하나의_값이라도_비어있다면_400에러를_리턴한() {
네이밍 확인좀 해주세요 :)

2019-12-17 10:13 UTC, pkch93 commented on src/main/java/woowacrew/feed/controller/FeedApiController.java
> +    public ResponseEntity<FeedSourceDto> registerFeedSource(@Valid FeedSourceDto feedSourceDto) {
Dto 네이밍 컨벤션을 ~ResponseDto나 ~RequestDto로 맞추자는 걸로 기억하는데 Request나 Response에 둘다 사용해서 FeedSourceDto로 명명한건가요?

2019-12-17 10:13 UTC, pkch93 commented on src/main/java/woowacrew/feed/controller/FeedApiController.java
> +    public ResponseEntity<FeedArticleResponseDtos> findAllFeedArticles
전반적으로 저희 controller method 네이밍 컨벤션과 동떨어져 보여요.
[https://www.slipp.net/questions/79](https://www.slipp.net/questions/79)에 따르면 위 메서드는 list가 되어야할 것 같아요.

2019-12-17 10:13 UTC, pkch93 commented on src/main/java/woowacrew/feed/domain/FeedSource.java
> +public class FeedSource {
하나의 피드 소스는 여러 피드 게시글에 참조될 수 있는건가요?

2019-12-17 10:51 UTC, vsh123 commented on src/main/java/woowacrew/feed/controller/FeedApiController.java
> +    public ResponseEntity<FeedSourceDto> registerFeedSource(@Valid FeedSourceDto feedSourceDto) {
맞아요! Request와 Response에 대해서 모두 동일한 필드로 주고받는 Dto기 때문에 하나로 했어요~
혹시 이 부분에 대해서 어떻게 생각하시나요?

2019-12-17 12:41 UTC, hyojaekim reviewed
테스트 메소드명이 영어, 한글 왔다리 갔다리 하네요 ㅎ
빠르게 잘 구현하셨습니다! 💯

2019-12-17 12:41 UTC, hyojaekim commented on src/main/java/woowacrew/feed/controller/FeedApiController.java
> +    public ResponseEntity<FeedSourceDto> registerFeedSource(@Valid FeedSourceDto feedSourceDto) {
핑퐁 Dto

2019-12-17 12:41 UTC, hyojaekim commented on src/main/java/woowacrew/feed/dto/FeedArticleResponseDto.java
> +    public void setTitle(String title) {
모든 값들을 생성자로 주입받고 있는데 setter를 넣은 이유가 있나요??

2019-12-17 12:41 UTC, hyojaekim commented on src/main/java/woowacrew/feed/service/FeedInternalService.java
> +                .map(source -> new RssReader(source.getSourceUrl()).getFeedArticle(source))
RssReader에게 FeedSource를 주는건 어떨까요?

2019-12-17 12:42 UTC, hyojaekim commented on src/main/java/woowacrew/feed/controller/FeedApiController.java
> +    public ResponseEntity<FeedSourceDto> registerFeedSource(@Valid FeedSourceDto feedSourceDto) {
핑퐁 DTO네요

2019-12-17 12:42 UTC, hyojaekim commented
혹시 테스트 다 돌아가나요? ㅠ

2019-12-17 15:51 UTC, vsh123 commented on src/main/java/woowacrew/feed/dto/FeedArticleResponseDto.java
> +    public void setTitle(String title) {
생성자 주입보다 modelMapper를 이용해서 주입하고 있어요!
다만 setFeedSourceDto()같이 Dto를 매핑해줘야하하는 경우에 setter를 사용해서 주입하고 있어요!! 불필요한 setter는 안만드는게 낫다고 생각하시나요?

2019-12-18 04:32 UTC, hyojaekim approved these changes
수고하셨습니다 :)

2019-12-18 04:59 UTC, pkch93 approved these changes
고생했어요 :+1: 간단한 피드백 하나만 남겼어요. 확인 부탁드려요!

2019-12-18 04:59 UTC, pkch93 commented on src/main/java/woowacrew/feed/domain/FeedArticles.java
> +public class FeedArticles {
:+1:

2019-12-18 04:59 UTC, pkch93 commented on src/main/java/woowacrew/feed/domain/FeedArticles.java
> +        return feedArticles;
일급 컬렉션의 컬렉션을 그대로 사용하도록 노출하기보단 `Collections.unmodifiableList()`로 노출하는건 어떤가요?

2019-12-18 04:59 UTC, pkch93 commented on src/test/java/woowacrew/feed/domain/FeedArticleRepositoryTest.java
> +        List<FeedArticle> result = feedArticleRepository.findByFeedSource(feedSource);
직접 작성한 쿼리메서드에 대한 테스트 :+1:

2019-12-18 04:59 UTC, pkch93 commented on src/main/java/woowacrew/feed/controller/FeedApiController.java
> +    public ResponseEntity<FeedArticleResponseDtos> list
피드백 반영 :+1:

2019-12-18 05:13 UTC, merged