feat: 슬랙 메세지 저장 기능 추가
WoowaCrew/WoowaCrew pull request #234
Opened 2020-01-09 01:35 UTC by hyojaekim

resolved #224

2020-01-09 10:06 UTC, oeeen requested changes
코드가 이해 안되는 부분이 약간 있어서 좀 더 확인후에 추가하겠습니다.

2020-01-09 10:06 UTC, oeeen commented on .github/workflows/build-check.yml
> +      run: echo "$github_secret" > ./src/main/resources/github.yml | echo "$slack_secret" > ./src/main/resources/slack.yml | echo "$slack_test_secret" > ./src/test/resources/slack.yml
👍

2020-01-09 10:06 UTC, oeeen commented on src/acceptance-test/java/woowacrew/article/slack/controller/SlackMessageApiControllerTest.java
> +class SlackMessageApiControllerTest {
API Test에 REST Docs 적용해주세요

2020-01-09 10:06 UTC, oeeen commented on src/main/java/woowacrew/article/slack/service/SlackMessageInternalService.java
> +            throw new CreateSlackMessageFailException();
connect()에서 IOException 발생 시 custom exception 던지고 로그에는 어떤 이유로 실패했는지 남기지 않아도 되나요?
Exception 발생 시 Logger로 따로 기록하지 않아도 로그에 남나요? (잘 몰라서 질문 드립니다.)

2020-01-09 10:06 UTC, oeeen commented on src/test/java/woowacrew/article/slack/service/SlackMessageInternalServiceTest.java
> +        String invalidToken = testSlackConfig.getToken();
정상적..인데 invalid?

2020-01-09 13:14 UTC, vsh123 approved these changes
좋은 내용 잘봤습니다 :)

2020-01-09 13:14 UTC, vsh123 commented on src/acceptance-test/java/woowacrew/article/slack/controller/SlackMessageApiControllerTest.java
> +    private TestSlackConfig slackConfig;
TestSlackConfig를 받는것보다는 SlackConfig를 Autowired하되 test의 값이 들어가도록 설정하면 어떨까요?
SlackConfig를 인터페이스로 빼는것도 방법중에 하나가 될 수 있겠네요

2020-01-09 13:14 UTC, vsh123 commented on src/main/java/woowacrew/article/slack/controller/SlackMessageApiController.java
> +    public void save(SlackMessageRequestDto slackMessageRequestDto) {
`ResponseEntity<Void>` 로 리턴하는게 좀 더 나을 것 같아요~

2020-01-09 13:14 UTC, vsh123 commented on src/main/java/woowacrew/article/slack/domain/SlackFile.java
> +    @Lob
Lob으로 설정한 이유가 있나요? path가 너무 길지 않다면 그냥 String으로 해도 괜찮을 것같아여!

2020-01-09 13:14 UTC, vsh123 commented on src/main/java/woowacrew/article/slack/service/SlackMessageInternalService.java
> +            session.connect();
connect()에 대한 close()는 없어도 괜찮은가요? 만약 필요하다면 try-catch-resources로 하면 좋을것 같네요

2020-01-09 13:55 UTC, hyojaekim commented on src/main/java/woowacrew/article/slack/service/SlackMessageInternalService.java
> +            throw new CreateSlackMessageFailException();
로그 남기도록 수정하겠습니다 👍 
중요한 예외인데 신중하지 못했네요 ㅠ

2020-01-09 14:06 UTC, hyojaekim commented on src/main/java/woowacrew/article/slack/service/SlackMessageInternalService.java
> +            session.connect();
disconnect가 있었네요 👍 
SlackSession에 AuthCloseable가 없어서 직접 닫아줬습니다 👍

2020-01-09 14:12 UTC, hyojaekim commented on src/main/java/woowacrew/article/slack/domain/SlackFile.java
> +    @Lob
그냥 String으로도 충분한 것 같습니다 💯

2020-01-10 01:22 UTC, hyojaekim commented on src/acceptance-test/java/woowacrew/article/slack/controller/SlackMessageApiControllerTest.java
> +    private TestSlackConfig slackConfig;
현재 메인에 있는 SlackConfig는 필드가 토큰 밖에 존재하지 않는데
SlackConfig를 사용하게 되면 테스트를 위해 불필요한 필드를 추가해야 해서 TestSlackConfig를 만들어줬는데 좋은 방법이 있을까요?

2020-01-10 02:03 UTC, hyojaekim commented on src/acceptance-test/java/woowacrew/article/slack/controller/SlackMessageApiControllerTest.java
> +class SlackMessageApiControllerTest {
네~!

2020-01-10 04:04 UTC, oeeen approved these changes
💯

2020-01-10 04:40 UTC, merged